name: Build and Deploy PySide6 QML App on Windows
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
 
    - name: Install PySide6 and QML dependencies
      run: pip install PySide6 --extra-index-url https://repo.pypi.org/simple/
 
    - name: Build QML files
      run: |
        cd path/to/your/qml/files
        pyside6-rcc resources.qrc -o resources.py
        pyside6-lupdate your_qml_app.pro
    - name: Deploy QML App
      uses: wslyvh/upload-artifact@master
      with:
        path: path/to/your/qml/files/your_qml_app.exe
        name: qml-app-artifact
 
  deploy:
    runs-on: self-hosted
    needs: build
    if: github.ref == 'refs/heads/main'
 
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: qml-app-artifact
        path: ./
 
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARTIFACT_NAME: qml-app-artifact
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_DIR: ${{ secrets.REMOTE_DIR }}